"""Inventory CSV import for the owned-asset batch.

Parses the IRES inventory export (docs/designs/owned-asset-exit-analysis.md,
"CSV input mapping"): a few preamble rows, one header row, one row per
property (cells may span lines), then a "Generated By" footer. Excel files
are converted to CSV in the browser (N2), so this module only sees CSV text.

Also provides address normalization and matching used by the optional loans
CSV (D5) and by loan-statement matching (N3 / N-design D7).
"""
from __future__ import annotations

import csv
import io
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Optional

MAX_BYTES = 2 * 1024 * 1024       # E10
MAX_ROWS = 500                    # E10

# Canonical field -> accepted header names (case-insensitive, whitespace-trimmed)
COLUMN_ALIASES = {
    "portfolio": ["portfolio name", "portfolio"],
    "address_line": ["building name", "address", "property address", "street address"],
    "city": ["building city", "city"],
    "state": ["state", "building state"],
    "status": ["status", "occupancy"],
    "vacant_since": ["rehab: move-out/key returned date", "move-out date", "vacant since"],
    "list_price": ["marketing: list price", "list price"],
    "goal_price": ["marketing: goal", "goal"],
    "arv": ["marketing: comps", "comps", "arv"],
    "value_as_of": ["marketing: zillow value updated", "value updated"],
    "sale_status": ["sale status"],
    "rehab_status": ["rehab: rehab status", "rehab status"],
    "rehab_quote": ["rehab: rehab quote amount", "rehab quote", "rehab budget"],
    "rehab_notes": ["rehab: property notes", "property notes", "notes"],
    "mechanical_notes": ["mechanical notes:", "mechanical notes"],
    "tax_winter": ["property tax fall/winter amount due:", "property tax fall/winter amount due", "winter tax"],
    "tax_summer": ["property tax spring/summer amount due:", "property tax spring/summer amount due", "summer tax"],
    "annual_tax": ["annual tax", "annual property tax"],
    "history_notes": ["deactivation date/notes", "history notes"],
    "client": ["refering client", "referring client", "client"],
    # Optional columns IRES may add (D5, M8)
    "loan_payoff": ["loan payoff", "loan balance", "payoff", "release amount"],
    "loan_rate": ["loan rate", "interest rate", "rate"],
    "loan_pi": ["loan p&i", "p&i", "monthly p&i", "loan payment"],
    "investor_payback": ["investor payback", "investor payoff"],
    "cost_basis": ["cost basis", "basis"],
    "annual_insurance": ["annual insurance", "insurance"],
    "beds": ["beds", "bedrooms"],
    "baths": ["baths", "bathrooms"],
    "sqft": ["sqft", "square feet", "sq ft"],
    "year_built": ["year built"],
}
REQUIRED = ["address_line", "city", "arv", "rehab_quote"]
REQUIRED_TAX = (("tax_winter", "tax_summer"), ("annual_tax",))


class ImportError_(ValueError):
    """Upload-level problem: returned to the user as a 413/422 (E10)."""

    def __init__(self, status: int, message: str, missing: Optional[list] = None):
        super().__init__(message)
        self.status = status
        self.message = message
        self.missing = missing or []


@dataclass
class ImportedRow:
    row_number: int
    fields: dict
    flags: list = field(default_factory=list)
    skipped_pending: bool = False

    @property
    def address(self) -> str:
        return self.fields.get("address_line") or ""


# ── parsing helpers ─────────────────────────────────────────────────────────

def decode(data: bytes) -> str:
    """UTF-8 (with or without BOM), falling back to cp1252 (E10)."""
    for enc in ("utf-8-sig", "cp1252"):
        try:
            return data.decode(enc)
        except UnicodeDecodeError:
            continue
    raise ImportError_(422, "File is not readable text (expected CSV in UTF-8 or Windows encoding)")


def parse_money(value) -> Optional[float]:
    """'$1,234.56 ' -> 1234.56; '' / '$0.00' handling is the caller's job."""
    if value is None:
        return None
    s = str(value).strip().replace("$", "").replace(",", "")
    if s in ("", "-"):
        return None
    negative = s.startswith("(") and s.endswith(")")
    s = s.strip("()")
    try:
        v = float(s)
    except ValueError:
        return None
    return -v if negative else v


def parse_percent(value) -> Optional[float]:
    if value is None:
        return None
    s = str(value).strip().replace("%", "")
    try:
        return float(s)
    except ValueError:
        return None


def parse_date(value) -> Optional[date]:
    s = (value or "").strip()
    for fmt in ("%m/%d/%Y", "%m/%d/%y", "%Y-%m-%d", "%m.%d.%Y", "%m.%d.%y"):
        try:
            return datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None


def _norm_header(h: str) -> str:
    return re.sub(r"\s+", " ", (h or "").strip().lower())


def _map_headers(header: list[str]) -> dict[str, int]:
    lookup = {}
    normalized = [_norm_header(h) for h in header]
    for canon, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            if alias in normalized:
                lookup[canon] = normalized.index(alias)
                break
    return lookup


def _find_header_row(rows: list[list[str]]) -> int:
    for i, row in enumerate(rows[:30]):
        norm = {_norm_header(c) for c in row}
        if norm & set(COLUMN_ALIASES["address_line"]) and norm & set(COLUMN_ALIASES["city"]):
            return i
    raise ImportError_(422, "Couldn't find the header row (expected columns like 'Building Name' and 'Building City')",
                       missing=["Building Name", "Building City"])


# ── address normalization and matching (D5, N-design D7) ───────────────────

SUFFIXES = {
    "street": "st", "st": "st", "avenue": "ave", "ave": "ave", "av": "ave", "drive": "dr", "dr": "dr",
    "road": "rd", "rd": "rd", "court": "ct", "ct": "ct", "lane": "ln", "ln": "ln", "boulevard": "blvd",
    "blvd": "blvd", "place": "pl", "pl": "pl", "circle": "cir", "cir": "cir", "terrace": "ter",
    "ter": "ter", "highway": "hwy", "hwy": "hwy", "parkway": "pkwy", "pkwy": "pkwy",
}
DIRECTIONALS = {"north": "n", "south": "s", "east": "e", "west": "w", "n": "n", "s": "s", "e": "e", "w": "w"}
UNIT_WORDS = {"apt", "unit", "#", "ste", "suite"}


def normalize_address(line: str) -> dict:
    """Split into number / street tokens / unit. Handles both '123 Main St'
    and IRES's 'Main 123' ordering."""
    s = re.sub(r"[.,]", " ", (line or "").lower())
    s = s.replace("#", " # ")
    tokens = [t for t in s.split() if t]
    unit = None
    for i, t in enumerate(tokens):
        if t in UNIT_WORDS and i + 1 < len(tokens):
            unit = tokens[i + 1]
            tokens = tokens[:i] + tokens[i + 2:]
            break
    number = None
    for i, t in enumerate(tokens):
        if re.fullmatch(r"\d+[a-z]?", t) and number is None:
            number = t
            tokens = tokens[:i] + tokens[i + 1:]
            break
    street = []
    for t in tokens:
        if t in DIRECTIONALS:
            street.append(DIRECTIONALS[t])
        elif t in SUFFIXES:
            continue            # suffix differences never block a match
        else:
            street.append(t)
    return {"number": number, "street": " ".join(street), "unit": unit}


def match_tier(a_line: str, a_city: str, b_line: str, b_city: str) -> str:
    """'exact' | 'likely' | 'none' (N-design D7)."""
    a, b = normalize_address(a_line), normalize_address(b_line)
    if not a["number"] or a["number"] != b["number"] or not a["street"] or a["street"] != b["street"]:
        # allow street-name containment ('kingsville' vs 'kingsville ave' already stripped)
        return "none"
    if (a["unit"] or None) != (b["unit"] or None):
        return "likely"
    ca, cb = (a_city or "").strip().lower(), (b_city or "").strip().lower()
    if ca and cb and ca == cb:
        return "exact"
    return "likely"


# ── inventory parsing ──────────────────────────────────────────────────────

FORFEITURE_RE = re.compile(r"\b(lc|l/c|land contract)\s+forfeiture\b", re.I)
NO_REHAB_RE = re.compile(r"\bno rehab\b", re.I)


def _row_flags(f: dict, run_date: date) -> list[str]:
    flags = []
    if not f.get("arv"):
        flags.append("Estimated ARV")
    if f.get("rehab_quote") is None:
        flags.append("Unknown rehab")
    value_as_of = f.get("value_as_of")
    if value_as_of and (run_date - value_as_of).days > 183:
        flags.append("Stale value")
    if not f.get("loan_payoff"):
        flags.append("No loan entered")
    if f.get("lc_forfeiture_history"):
        flags.append("LC forfeiture history")
    if f.get("cost_basis") is None:
        flags.append("No cost basis")
    return flags


def parse_inventory(data: bytes, run_date: Optional[date] = None) -> list[ImportedRow]:
    """Parse an inventory CSV into rows. Raises ImportError_ on upload-level problems."""
    run_date = run_date or date.today()
    if len(data) > MAX_BYTES:
        raise ImportError_(413, "File is larger than 2 MB")
    text = decode(data)
    rows = list(csv.reader(io.StringIO(text)))
    header_i = _find_header_row(rows)
    cols = _map_headers(rows[header_i])
    missing = [c for c in REQUIRED if c not in cols]
    if not any(all(c in cols for c in group) for group in REQUIRED_TAX):
        missing.append("tax_winter/tax_summer or annual_tax")
    if missing:
        names = {"address_line": "Building Name", "city": "Building City", "arv": "Marketing: Comps",
                 "rehab_quote": "Rehab: Rehab Quote Amount",
                 "tax_winter/tax_summer or annual_tax": "Property Tax Fall/Winter + Spring/Summer (or Annual Tax)"}
        raise ImportError_(422, "Missing required columns", missing=[names.get(m, m) for m in missing])

    out: list[ImportedRow] = []
    for idx, raw in enumerate(rows[header_i + 1:], start=header_i + 2):
        if not raw or not any(c.strip() for c in raw):
            continue
        if raw[0].strip().lower().startswith("generated by"):
            break

        def get(name):
            i = cols.get(name)
            return raw[i].strip() if i is not None and i < len(raw) else ""

        address = get("address_line")
        if not address:
            continue
        f: dict = {
            "portfolio": get("portfolio") or None,
            "address_line": address,
            "city": get("city"),
            "state": (get("state") or "MI").upper(),
            "status": get("status") or None,
            "vacant_since": parse_date(get("vacant_since")),
            "list_price": parse_money(get("list_price")) or None,
            "goal_price": parse_money(get("goal_price")) or None,
            "arv": parse_money(get("arv")) or None,                   # $0 = unknown -> estimate
            "value_as_of": parse_date(get("value_as_of")),
            "sale_status": get("sale_status") or None,
            "rehab_status": get("rehab_status") or None,
            "notes": "\n".join(x for x in (get("rehab_notes"), get("mechanical_notes")) if x) or None,
            "history_notes": get("history_notes") or None,
            "client": get("client") or None,
        }
        quote = parse_money(get("rehab_quote"))
        f["rehab_quote"] = quote if quote else None                  # $0 / "NO REHAB" = unknown, not zero
        if "annual_tax" in cols and get("annual_tax"):
            f["annual_tax"] = parse_money(get("annual_tax"))
        else:
            parts = [parse_money(get("tax_winter")), parse_money(get("tax_summer"))]
            f["annual_tax"] = sum(p for p in parts if p) if any(parts) else None
        for name in ("loan_payoff", "loan_pi", "investor_payback", "cost_basis", "annual_insurance", "sqft"):
            v = parse_money(get(name)) if name in cols else None
            f[name] = v
        f["loan_rate"] = parse_percent(get("loan_rate")) if "loan_rate" in cols else None
        for name, cast in (("beds", float), ("baths", float), ("year_built", int)):
            v = get(name) if name in cols else ""
            try:
                f[name] = cast(float(v)) if v else None
            except ValueError:
                f[name] = None
        f["lc_forfeiture_history"] = bool(FORFEITURE_RE.search(f.get("history_notes") or "")
                                          or FORFEITURE_RE.search(f.get("notes") or ""))
        pending = ((f.get("sale_status") or "").strip().lower() == "pending"
                   or (f.get("rehab_status") or "").strip().lower() == "pending sale")
        row = ImportedRow(row_number=idx, fields=f, skipped_pending=pending)
        row.flags = _row_flags(f, run_date) + (["Pending sale"] if pending else [])
        if f["vacant_since"]:
            f["months_vacant"] = max(0, (run_date - f["vacant_since"]).days // 30)
        out.append(row)
        if len(out) > MAX_ROWS:
            raise ImportError_(422, f"More than {MAX_ROWS} properties in one file")
    if not out:
        raise ImportError_(422, "No property rows found under the header")
    return out


def parse_loans(data: bytes) -> list[dict]:
    """Optional second 'loans' CSV (D5): Building Name, payoff, rate, P&I (+ city optional)."""
    text = decode(data)
    rows = list(csv.reader(io.StringIO(text)))
    header_i = None
    for i, row in enumerate(rows[:30]):
        norm = {_norm_header(c) for c in row}
        if norm & set(COLUMN_ALIASES["address_line"]) and norm & set(COLUMN_ALIASES["loan_payoff"]):
            header_i = i
            break
    if header_i is None:
        raise ImportError_(422, "Loans file needs an address column and a payoff column",
                           missing=["Building Name", "Loan Payoff"])
    cols = _map_headers(rows[header_i])
    loans = []
    for raw in rows[header_i + 1:]:
        if not raw or not any(c.strip() for c in raw):
            continue

        def get(name):
            i = cols.get(name)
            return raw[i].strip() if i is not None and i < len(raw) else ""

        if not get("address_line"):
            continue
        loans.append({"address_line": get("address_line"), "city": get("city"),
                      "loan_payoff": parse_money(get("loan_payoff")),
                      "loan_rate": parse_percent(get("loan_rate")),
                      "loan_pi": parse_money(get("loan_pi"))})
    return loans


def apply_loans(rows: list[ImportedRow], loans: list[dict]) -> list[dict]:
    """Attach loan data by address match; returns unmatched loan entries."""
    unmatched = []
    for loan in loans:
        best, best_tier = None, "none"
        for row in rows:
            tier = match_tier(loan["address_line"], loan.get("city", ""), row.address, row.fields.get("city", ""))
            if tier == "exact" or (tier == "likely" and best_tier == "none"):
                best, best_tier = row, tier
                if tier == "exact":
                    break
        if best is None:
            unmatched.append(loan)
            continue
        for k in ("loan_payoff", "loan_rate", "loan_pi"):
            if loan.get(k) is not None:
                best.fields[k] = loan[k]
        best.fields["loan_match"] = best_tier
        best.flags = [f for f in best.flags if f != "No loan entered"]
    return unmatched


def row_to_inputs_dict(row: ImportedRow) -> dict:
    """Map an imported row to owned_asset.PropertyInputs keyword arguments + sources."""
    f = row.fields
    sources = {}

    def src(name, value):
        sources[name] = "USER" if value is not None else "DEFAULT"
        return value

    return {
        "address": f"{f['address_line']}",
        "city": f.get("city") or "",
        "state": f.get("state") or "MI",
        "occupancy": "vacant" if (f.get("status") or "vacant").lower().startswith("vacant") else "occupied",
        "arv": src("arv", f.get("arv")),
        "rehab_budget": src("rehab_budget", f.get("rehab_quote")),
        "annual_tax": src("annual_tax", f.get("annual_tax")),
        "annual_insurance": src("annual_insurance", f.get("annual_insurance")),
        "utilities_monthly": f.get("utilities_monthly"),
        "maintenance_monthly": f.get("maintenance_monthly"),
        "security_monthly": f.get("security_monthly"),
        "grass_snow_monthly": f.get("grass_snow_monthly"),
        "other_holding_monthly": f.get("other_holding_monthly"),
        "loan_payoff": f.get("loan_payoff") or 0.0,
        "loan_rate_pct": f.get("loan_rate") or 0.0,
        "loan_pi": f.get("loan_pi") or 0.0,
        "investor_payback": f.get("investor_payback") or 0.0,
        "cost_basis": src("cost_basis", f.get("cost_basis")),
        "beds": src("beds", f.get("beds")),
        "baths": src("baths", f.get("baths")),
        "sqft": src("sqft", f.get("sqft")),
        "year_built": src("year_built", f.get("year_built")),
        "lc_forfeiture_history": bool(f.get("lc_forfeiture_history")),
        "sources": sources,
    }
